from datetime import UTC, datetime, timedelta

from fastapi import APIRouter, Depends, Query, Request
from pydantic import BaseModel
from sqlalchemy.orm import Session
from fastapi.responses import Response

from app.core.security import CurrentUser
from app.db.deps import get_db
from app.schemas.base import ApiResponse
from app.schemas.enums import ReportType
from app.schemas.report import (
	DoctorReportOut,
	GenerateReportRequest,
	GeneralReportOut,
	PDFDownloadUrlOut,
	PatientReportOut,
	ReportOut,
	ShareReportRequest,
)
from app.services import report_service
from app.core.config import get_settings

router = APIRouter(prefix="/reports", tags=["reports"])


@router.post(
	"/generate",
	response_model=ApiResponse[ReportOut],
	summary="Generate and persist a report + signed PDF URL",
)
def generate_report(
	body: GenerateReportRequest,
	current_user: CurrentUser,
	db: Session = Depends(get_db),
) -> ApiResponse[ReportOut]:
	result = report_service.generate_report(db, current_user, body.caseId, body.reportType)
	return ApiResponse.ok(result)


@router.get(
	"",
	response_model=ApiResponse[list[ReportOut]],
	summary="List reports for a case",
)
def list_reports(
	case_id: str,
	current_user: CurrentUser,
	db: Session = Depends(get_db),
) -> ApiResponse[list[ReportOut]]:
	result = report_service.list_reports(db, current_user, case_id)
	return ApiResponse.ok(result)


@router.get(
	"/{report_id}",
	response_model=ApiResponse[ReportOut],
	summary="Get a report by id",
)
def get_report(
	report_id: str,
	current_user: CurrentUser,
	db: Session = Depends(get_db),
) -> ApiResponse[ReportOut]:
	result = report_service.get_report(db, current_user, report_id)
	return ApiResponse.ok(result)


@router.get(
	"/{case_id}/doctor",
	response_model=ApiResponse[DoctorReportOut],
	summary="Get doctor-facing JSON report",
)
def get_doctor_report(
	case_id: str,
	current_user: CurrentUser,
	db: Session = Depends(get_db),
) -> ApiResponse[DoctorReportOut]:
	result = report_service.get_case_report_json(db, current_user, case_id, ReportType.DOCTOR)
	return ApiResponse.ok(result)


@router.get(
	"/{case_id}/patient",
	response_model=ApiResponse[PatientReportOut],
	summary="Get patient-friendly JSON report",
)
def get_patient_report(
	case_id: str,
	current_user: CurrentUser,
	db: Session = Depends(get_db),
) -> ApiResponse[PatientReportOut]:
	result = report_service.get_case_report_json(db, current_user, case_id, ReportType.PATIENT)
	return ApiResponse.ok(result)


@router.get(
	"/{case_id}/pdf",
	response_model=ApiResponse[PDFDownloadUrlOut],
	summary="Get time-limited signed PDF URL",
)
def get_case_pdf_url(
	case_id: str,
	request: Request,
	current_user: CurrentUser,
	db: Session = Depends(get_db),
	report_type: ReportType = Query(default=ReportType.DOCTOR, alias="type"),
) -> ApiResponse[PDFDownloadUrlOut]:
	try:
		result = report_service.get_case_pdf_url(db, current_user, case_id, report_type)
		return ApiResponse.ok(result)
	except Exception as exc:
		# Only fallback for unexpected runtime errors (e.g. Cloudinary/weasyprint issues).
		# Preserve intentional HTTPExceptions.
		from fastapi import HTTPException
		if isinstance(exc, HTTPException):
			raise
		base = str(request.base_url).rstrip("/")
		# Provide a backend-served PDF endpoint as a fallback URL.
		settings = get_settings()
		expires_at = datetime.now(UTC) + timedelta(seconds=settings.PDF_DOWNLOAD_EXPIRY_SECONDS)
		return ApiResponse.ok(
			PDFDownloadUrlOut(
				url=f"{base}/api/v1/reports/{case_id}/pdf-fallback?type={report_type.value}",
				expiresAt=expires_at.isoformat(),
			)
		)


@router.get(
	"/{case_id}/pdf-fallback",
	summary="Fallback PDF (generated by backend) when Cloudinary fails",
)
def pdf_fallback(
	case_id: str,
	current_user: CurrentUser,
	db: Session = Depends(get_db),
	report_type: ReportType = Query(default=ReportType.DOCTOR, alias="type"),
) -> Response:
	# Load case/patient for labels and permission checks.
	case, patient, _analysis = report_service._load_case_and_analysis(db, current_user, case_id)  # type: ignore[attr-defined]
	pdf_bytes = report_service.render_fallback_ai_pdf_bytes(
		report_type,
		case_id=str(case.id),
		patient_name=getattr(patient, "full_name", "") or "",
		image_url=getattr(case, "image_url", "") or "",
	)
	filename = f"fundusai-{case_id}-{report_type.value}-fallback.pdf"
	return Response(
		content=pdf_bytes,
		media_type="application/pdf",
		headers={"Content-Disposition": f'inline; filename="{filename}"'},
	)


@router.get(
	"/{case_id}/general",
	response_model=ApiResponse[GeneralReportOut],
	summary="Get combined case detail + analysis result (general report)",
)
def get_general_report(
	case_id: str,
	current_user: CurrentUser,
	db: Session = Depends(get_db),
) -> ApiResponse[GeneralReportOut]:
	result = report_service.get_general_report(db, current_user, case_id)
	return ApiResponse.ok(result)


@router.post(
	"/{case_id}/share",
	response_model=ApiResponse[dict],
	summary="Share report to patient email",
)
def share_report(
	case_id: str,
	body: ShareReportRequest,
	current_user: CurrentUser,
	db: Session = Depends(get_db),
) -> ApiResponse[dict]:
	result = report_service.share_report(db, current_user, case_id, body.email)
	return ApiResponse.ok(result)
