'use client'

import { useState, useEffect, useRef } from 'react'
import { Bot, ChevronDown, ChevronUp } from 'lucide-react'
import { cn } from '@/lib/cn'
import { Badge } from '@/Components/ui/Badge'

export interface RAGJustificationCardProps {
  justification: string
  animate?: boolean
  compact?: boolean
  className?: string
}

export const RAGJustificationCard = ({
  justification,
  animate = true,
  compact = false,
  className,
}: RAGJustificationCardProps) => {
  const [displayedText, setDisplayedText] = useState(animate ? '' : justification)
  const [isAnimating, setIsAnimating] = useState(animate)
  const [isExpanded, setIsExpanded] = useState(false)
  const [needsTruncation, setNeedsTruncation] = useState(false)
  const textRef = useRef<HTMLParagraphElement>(null)

  // Typing animation
  useEffect(() => {
    if (!animate) return
    let idx = 0
    const interval = setInterval(() => {
      idx++
      if (idx >= justification.length) {
        setDisplayedText(justification)
        setIsAnimating(false)
        clearInterval(interval)
      } else {
        setDisplayedText(justification.slice(0, idx))
      }
    }, 20)
    return () => clearInterval(interval)
  }, [justification, animate])

  // Check if truncation needed
  useEffect(() => {
    if (textRef.current && !isAnimating) {
      setNeedsTruncation(textRef.current.scrollHeight > textRef.current.clientHeight)
    }
  }, [displayedText, isAnimating])

  return (
    <div
      className={cn(
        'bg-[var(--bg-elevated)] border border-[var(--border-strong)] rounded-[4px]',
        'overflow-hidden',
        className,
      )}
    >
      {/* Header */}
      <div className="flex items-center justify-between px-4 py-3 border-b border-[var(--border)]">
        <div className="flex items-center gap-2">
          <span className="font-condensed font-medium text-[11px] uppercase tracking-[0.08em] text-[var(--text-muted)]">
            AI Medical Justification
          </span>
          <Badge variant="info" size="sm">
            <Bot size={10} className="mr-0.5" />
            AI
          </Badge>
        </div>
      </div>

      {/* Body */}
      <div className="px-4 py-4">
        {!compact && (
          <p className="text-[10px] font-condensed text-[var(--text-muted)] mb-3">
            Generated by RAG-enhanced clinical knowledge base
          </p>
        )}

        {/* Blockquote-style text */}
        <div className="border-l-2 border-[var(--accent)] pl-4">
          <p
            ref={textRef}
            className={cn(
              'text-[0.875rem] leading-[1.7] text-[var(--text-secondary)] italic',
              !isExpanded && !isAnimating && 'line-clamp-3',
            )}
          >
            &ldquo;{displayedText}&rdquo;
            {isAnimating && (
              <span className="inline-block w-0.5 h-4 bg-[var(--accent)] ml-0.5 animate-pulse-glow align-text-bottom" />
            )}
          </p>
        </div>

        {/* Expand/collapse */}
        {needsTruncation && !isAnimating && (
          <button
            onClick={() => setIsExpanded(!isExpanded)}
            className={cn(
              'flex items-center gap-1 mt-2 text-xs text-[var(--accent)]',
              'hover:underline cursor-pointer',
            )}
          >
            {isExpanded ? (
              <>Show less <ChevronUp size={12} /></>
            ) : (
              <>Read more <ChevronDown size={12} /></>
            )}
          </button>
        )}
      </div>

      {/* Disclaimer */}
      {!compact && (
        <div className="px-4 py-2.5 border-t border-[var(--border)] bg-[var(--bg-surface)]">
          <p className="text-[10px] text-[var(--text-muted)] leading-relaxed">
            This justification is AI-generated and should be reviewed by a qualified clinician before clinical decisions are made.
          </p>
        </div>
      )}
    </div>
  )
}
